import random

attempt=1
"""
Generate the random number between 1 and 10
"""
gen_random_num = random.randint(1,10)

while(attempt<=5):
    """venv
    """venv
    Request the user to enter some random to compare againse the random number 
    generated by the program
    """
    user_num = int(input ('Enter the number between 1 and 10:'))

    if(user_num==gen_random_num):
        print('You win!')
    elif(user_num < gen_random_num):
        print("You're thinking too small")
    else:
        print("You'are thinking too large")
    """
    Print the program generated random number on 4th att
    """
    if(attempt==4):
        print(f'Generated Random number {gen_random_num} ')
    attempt+=1
